version: "3.9"
services:
  frontend:
    build: ./frontend
    restart: always
    networks:
      - sso-net
  backend:
    build: ./backend
    restart: always
    volumes:
      - /var/log/sso/:/var/log/sso/
    depends_on:
      - frontend
      - surrealdb
    networks:
      - sso-net
  surrealdb:
    image: surrealdb/surrealdb:latest
    user: "0:0"
    command: start --log debug --user root --pass root --bind 0.0.0.0:9952 rocksdb:/data/db
    volumes:
      - surrealdb-data:/data/db
    restart: unless-stopped
    ports:
      - "9952:9952"
    networks:
      - sso-net

volumes:
  surrealdb-data:

networks:
  sso-net:
    driver: bridge