version: "3.9"
services:
  frontend:
    build: ./frontend
    restart: always
  backend:
    build: ./backend
    restart: always
    volumes:
      - /var/log/sso/:/var/log/sso/
    depends_on:
      - frontend
      - surrealdb
  surrealdb:
    image: surrealdb/surrealdb:latest
    user: "0:0"
    command: start --log debug --user root --pass root --bind 0.0.0.0:9952 rocksdb:/data/db
    volumes:
      - surrealdb-data:/data/db
    restart: unless-stopped

volumes:
  surrealdb-data: