version: "3.9"
services:
  frontend:
    build: ./frontend
    restart: always
  backend:
    build: ./backend
    restart: always
    volumes:
      - /var/log/sso/:/var/log/sso/
    depends_on:
      - frontend
      - surrealdb
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log debug --user root --pass root file:/data/db
    ports:
      - "9952:8000"
    volumes:
      - surrealdb-data:/data/db
    restart: unless-stopped

volumes:
  surrealdb-data: