name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Start SurrealDB
      uses: surrealdb/setup-surreal@v2
      with:
        surrealdb_version: latest
        surrealdb_port: 9952
        surrealdb_username: root
        surrealdb_password: root
        surrealdb_auth: false
        surrealdb_strict: false
        surrealdb_log: info
        surrealdb_additional_args: --allow-all
        surrealdb_retry_count: 120
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
