name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    services:
      surrealdb:
        image: surrealdb/surrealdb:latest
        options: --rm -p 9952:9952 -v /tmp/surrealdb_data:/var/lib/surrealdb
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
